# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(585, 565)
        self.tb_log = QtWidgets.QTextBrowser(Form)
        self.tb_log.setGeometry(QtCore.QRect(20, 30, 531, 121))
        self.tb_log.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tb_log.setObjectName("tb_log")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.label.setObjectName("label")
        self.btn_exit = QtWidgets.QPushButton(Form)
        self.btn_exit.setGeometry(QtCore.QRect(460, 520, 113, 32))
        self.btn_exit.setObjectName("btn_exit")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(200, 170, 175, 171))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_card6 = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_card6.setObjectName("btn_card6")
        self.gridLayout_2.addWidget(self.btn_card6, 1, 1, 1, 1)
        self.lb_card8 = QtWidgets.QLabel(self.layoutWidget)
        self.lb_card8.setObjectName("lb_card8")
        self.gridLayout_2.addWidget(self.lb_card8, 3, 0, 1, 1)
        self.btn_card8 = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_card8.setObjectName("btn_card8")
        self.gridLayout_2.addWidget(self.btn_card8, 3, 1, 1, 1)
        self.lb_card9 = QtWidgets.QLabel(self.layoutWidget)
        self.lb_card9.setObjectName("lb_card9")
        self.gridLayout_2.addWidget(self.lb_card9, 4, 0, 1, 1)
        self.lb_card5 = QtWidgets.QLabel(self.layoutWidget)
        self.lb_card5.setObjectName("lb_card5")
        self.gridLayout_2.addWidget(self.lb_card5, 0, 0, 1, 1)
        self.btn_card9 = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_card9.setObjectName("btn_card9")
        self.gridLayout_2.addWidget(self.btn_card9, 4, 1, 1, 1)
        self.lb_card7 = QtWidgets.QLabel(self.layoutWidget)
        self.lb_card7.setObjectName("lb_card7")
        self.gridLayout_2.addWidget(self.lb_card7, 2, 0, 1, 1)
        self.lb_card6 = QtWidgets.QLabel(self.layoutWidget)
        self.lb_card6.setObjectName("lb_card6")
        self.gridLayout_2.addWidget(self.lb_card6, 1, 0, 1, 1)
        self.btn_card7 = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_card7.setObjectName("btn_card7")
        self.gridLayout_2.addWidget(self.btn_card7, 2, 1, 1, 1)
        self.btn_card5 = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_card5.setObjectName("btn_card5")
        self.gridLayout_2.addWidget(self.btn_card5, 0, 1, 1, 1)
        self.layoutWidget_2 = QtWidgets.QWidget(Form)
        self.layoutWidget_2.setGeometry(QtCore.QRect(380, 170, 175, 171))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lb_card10 = QtWidgets.QLabel(self.layoutWidget_2)
        self.lb_card10.setObjectName("lb_card10")
        self.gridLayout_3.addWidget(self.lb_card10, 0, 0, 1, 1)
        self.btn_card10 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btn_card10.setObjectName("btn_card10")
        self.gridLayout_3.addWidget(self.btn_card10, 0, 1, 1, 1)
        self.lb_card11 = QtWidgets.QLabel(self.layoutWidget_2)
        self.lb_card11.setObjectName("lb_card11")
        self.gridLayout_3.addWidget(self.lb_card11, 1, 0, 1, 1)
        self.btn_card11 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btn_card11.setObjectName("btn_card11")
        self.gridLayout_3.addWidget(self.btn_card11, 1, 1, 1, 1)
        self.lb_card12 = QtWidgets.QLabel(self.layoutWidget_2)
        self.lb_card12.setObjectName("lb_card12")
        self.gridLayout_3.addWidget(self.lb_card12, 2, 0, 1, 1)
        self.btn_card12 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btn_card12.setObjectName("btn_card12")
        self.gridLayout_3.addWidget(self.btn_card12, 2, 1, 1, 1)
        self.lb_card13 = QtWidgets.QLabel(self.layoutWidget_2)
        self.lb_card13.setObjectName("lb_card13")
        self.gridLayout_3.addWidget(self.lb_card13, 3, 0, 1, 1)
        self.btn_card13 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btn_card13.setObjectName("btn_card13")
        self.gridLayout_3.addWidget(self.btn_card13, 3, 1, 1, 1)
        self.lb_card14 = QtWidgets.QLabel(self.layoutWidget_2)
        self.lb_card14.setObjectName("lb_card14")
        self.gridLayout_3.addWidget(self.lb_card14, 4, 0, 1, 1)
        self.btn_card14 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btn_card14.setObjectName("btn_card14")
        self.gridLayout_3.addWidget(self.btn_card14, 4, 1, 1, 1)
        self.lb_activeplayer = QtWidgets.QLabel(Form)
        self.lb_activeplayer.setGeometry(QtCore.QRect(30, 450, 351, 81))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.lb_activeplayer.setFont(font)
        self.lb_activeplayer.setObjectName("lb_activeplayer")
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 170, 175, 171))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lb_card0 = QtWidgets.QLabel(self.layoutWidget1)
        self.lb_card0.setObjectName("lb_card0")
        self.gridLayout.addWidget(self.lb_card0, 0, 0, 1, 1)
        self.btn_card0 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_card0.setObjectName("btn_card0")
        self.gridLayout.addWidget(self.btn_card0, 0, 1, 1, 1)
        self.lb_card1 = QtWidgets.QLabel(self.layoutWidget1)
        self.lb_card1.setObjectName("lb_card1")
        self.gridLayout.addWidget(self.lb_card1, 1, 0, 1, 1)
        self.btn_card1 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_card1.setObjectName("btn_card1")
        self.gridLayout.addWidget(self.btn_card1, 1, 1, 1, 1)
        self.lb_card2 = QtWidgets.QLabel(self.layoutWidget1)
        self.lb_card2.setObjectName("lb_card2")
        self.gridLayout.addWidget(self.lb_card2, 2, 0, 1, 1)
        self.btn_card2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_card2.setObjectName("btn_card2")
        self.gridLayout.addWidget(self.btn_card2, 2, 1, 1, 1)
        self.lb_card3 = QtWidgets.QLabel(self.layoutWidget1)
        self.lb_card3.setObjectName("lb_card3")
        self.gridLayout.addWidget(self.lb_card3, 3, 0, 1, 1)
        self.btn_card3 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_card3.setObjectName("btn_card3")
        self.gridLayout.addWidget(self.btn_card3, 3, 1, 1, 1)
        self.lb_card4 = QtWidgets.QLabel(self.layoutWidget1)
        self.lb_card4.setObjectName("lb_card4")
        self.gridLayout.addWidget(self.lb_card4, 4, 0, 1, 1)
        self.btn_card4 = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_card4.setObjectName("btn_card4")
        self.gridLayout.addWidget(self.btn_card4, 4, 1, 1, 1)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(280, 390, 281, 32))
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btn_next = QtWidgets.QPushButton(self.widget)
        self.btn_next.setObjectName("btn_next")
        self.gridLayout_4.addWidget(self.btn_next, 0, 2, 1, 1)
        self.btn_giveup = QtWidgets.QPushButton(self.widget)
        self.btn_giveup.setObjectName("btn_giveup")
        self.gridLayout_4.addWidget(self.btn_giveup, 0, 1, 1, 1)
        self.btn_discard = QtWidgets.QPushButton(self.widget)
        self.btn_discard.setObjectName("btn_discard")
        self.gridLayout_4.addWidget(self.btn_discard, 0, 0, 1, 1)
        self.widget1 = QtWidgets.QWidget(Form)
        self.widget1.setGeometry(QtCore.QRect(150, 350, 286, 31))
        self.widget1.setObjectName("widget1")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.btn_gettaiji = QtWidgets.QPushButton(self.widget1)
        self.btn_gettaiji.setObjectName("btn_gettaiji")
        self.gridLayout_5.addWidget(self.btn_gettaiji, 0, 2, 1, 1)
        self.btn_getyinyu = QtWidgets.QPushButton(self.widget1)
        self.btn_getyinyu.setObjectName("btn_getyinyu")
        self.gridLayout_5.addWidget(self.btn_getyinyu, 0, 0, 1, 1)
        self.btn_getyangyu = QtWidgets.QPushButton(self.widget1)
        self.btn_getyangyu.setObjectName("btn_getyangyu")
        self.gridLayout_5.addWidget(self.btn_getyangyu, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Game Log:"))
        self.btn_exit.setText(_translate("Form", "Exit"))
        self.btn_card6.setText(_translate("Form", "PushButton"))
        self.lb_card8.setText(_translate("Form", "9："))
        self.btn_card8.setText(_translate("Form", "PushButton"))
        self.lb_card9.setText(_translate("Form", "10："))
        self.lb_card5.setText(_translate("Form", "6："))
        self.btn_card9.setText(_translate("Form", "PushButton"))
        self.lb_card7.setText(_translate("Form", "8："))
        self.lb_card6.setText(_translate("Form", "7："))
        self.btn_card7.setText(_translate("Form", "PushButton"))
        self.btn_card5.setText(_translate("Form", "PushButton"))
        self.lb_card10.setText(_translate("Form", "11："))
        self.btn_card10.setText(_translate("Form", "PushButton"))
        self.lb_card11.setText(_translate("Form", "12："))
        self.btn_card11.setText(_translate("Form", "PushButton"))
        self.lb_card12.setText(_translate("Form", "13："))
        self.btn_card12.setText(_translate("Form", "PushButton"))
        self.lb_card13.setText(_translate("Form", "14："))
        self.btn_card13.setText(_translate("Form", "PushButton"))
        self.lb_card14.setText(_translate("Form", "15："))
        self.btn_card14.setText(_translate("Form", "PushButton"))
        self.lb_activeplayer.setText(_translate("Form", "TextLabel"))
        self.lb_card0.setText(_translate("Form", "1："))
        self.btn_card0.setText(_translate("Form", "PushButton"))
        self.lb_card1.setText(_translate("Form", "2："))
        self.btn_card1.setText(_translate("Form", "PushButton"))
        self.lb_card2.setText(_translate("Form", "3："))
        self.btn_card2.setText(_translate("Form", "PushButton"))
        self.lb_card3.setText(_translate("Form", "4："))
        self.btn_card3.setText(_translate("Form", "PushButton"))
        self.lb_card4.setText(_translate("Form", "5："))
        self.btn_card4.setText(_translate("Form", "PushButton"))
        self.btn_next.setText(_translate("Form", "NEXT"))
        self.btn_giveup.setText(_translate("Form", "不出牌"))
        self.btn_discard.setText(_translate("Form", "弃牌模式:ON"))
        self.btn_gettaiji.setText(_translate("Form", "抢夺太极"))
        self.btn_getyinyu.setText(_translate("Form", "抢夺阴鱼"))
        self.btn_getyangyu.setText(_translate("Form", "抢夺阳鱼"))

